# ----------------- #
#    Main Configs   #
# ----------------- #

# e.g: "http://example.com"
url: http://wiki.wutianqi.com
title: Tanky Woo's Wiki
keywords: wiki, makrdown, linux, python, cpp, ops, simiki
description: Tanky Woo's personal wiki, powered by vim and markdown. Focus on Python, C/C++, Linux, Ops-Dev, Gentoo, and so on.
author: Tanky Woo

# The catalog of theme.
theme: simple

# The base directory of the site.
# If base_dir is `None`, default site structure is:
#   ./
#   ├── _config.yml
#   ├── content
#   └── html
base_dir: 

# Set the makrdown files source, and output html files destination.
source: content
destination: html

default_ext: "md"

# TODO
# Replace the default home page with indexes.
default_home_page: 

# Open the code highlight feature.
pygments: true
