url: http://wiki.tankywoo.com
title: Wiki · Tanky Woo
keywords: wiki, makrdown, linux, python, cpp, ops, simiki
description: "Tanky Woo's personal wiki, powered by vim and markdown. Focus on Python, C/C++, Linux, Ops-Dev, Gentoo, and so on."
author: Tanky Woo
theme: yasimple_x2

category:
  - name: linux
    label: Linux/运维

##### Deploy #####
deploy:
  - type: rsync
    user: root
    host: 101.200.157.48
    dir: /opt/wiki.tankywoo.com/output
  - type: git
    remote: origin
    branch: gh-pages
