url: http://wiki.tankywoo.com
title: Wiki · Tanky Woo
keywords: wiki, makrdown, linux, python, cpp, ops, simiki
description: "Tanky Woo's personal wiki, powered by vim and markdown. Focus on Python, C/C++, Linux, Ops-Dev, Gentoo, and so on."
author: Tanky Woo
theme: yasimple
